In [2]:
#  Python NumPy Questions:
# Python NumPy (Array, Random, Math):
#  Write a Python program to print the NumPy
# version in your system.

import numpy as np
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [3]:
#  Write a Python program to reverse an array
# (first element becomes last).
print(arr1)
arr2 = arr1[::-1]
print(arr2)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [4]:
#  Write a Python program to convert a list and
# tuple into arrays.
lst1 = list(range(10))
tup1 = tuple(range(5,20))
arr1 = np.array(lst1)
arr2 = np.array(tup1)
print(arr1, '\n',arr2)

[0 1 2 3 4 5 6 7 8 9] 
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
#  Write a Python program to find common values
# between two arrays.

arr1 = np.arange(10)
arr2 = np.arange(11,21)
arr3 = np.intersect1d(arr1,arr2)
print(arr3)

[]


In [12]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [6]:
#  Write a Python program compare two arrays
# using numpy.

print(np.array_equiv(arr1,arr2))
print(np.array_equal(arr1,arr2))

False
False


In [7]:
#  Write a Python program to change the
# dimension of an array.
arr1 = np.arange(20)
print(arr1)
print(np.shape(arr1))
arr1.shape = (4,5)
print(np.shape(arr1))
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
(4, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [9]:
#  Write a Python program (using numpy) to sum
# of all the multiples of 3 or 5 below 100.
c = []
for x in range(1,100):
    if (x%3==0 or x%5==0):
        c.append(x)
c_array = np.array(c)
sum_array = np.sum(c_array)
print(sum_array)


2318


In [10]:
#  Write a Python program to convert a NumPy
# array into Python list structure.
print(c_array)
lst2 = list(c_array)
print(lst2)

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99]


In [11]:
#  Write a Python program to how to add an extra
# column to a numpy array.
np_array = np.random.randint(1,10,24).reshape(3,4,2)
print(np_array)
print('After adding extra column:')
np_array_modified = np_array.reshape(4,2,3)
print(np_array_modified)



[[[1 1]
  [5 4]
  [8 7]
  [6 6]]

 [[3 2]
  [5 9]
  [4 5]
  [6 9]]

 [[8 2]
  [3 9]
  [5 1]
  [9 4]]]
After adding extra column:
[[[1 1 5]
  [4 8 7]]

 [[6 6 3]
  [2 5 9]]

 [[4 5 6]
  [9 8 2]]

 [[3 9 5]
  [1 9 4]]]


In [12]:
# Write a Python program to check whether the numpy array is empty or not.
np_array = np.random.randint(1,10,24).reshape(3,4,2)
np_array1 = np.array([])
print(np_array.any())
print(np_array1.any())

True
False


In [13]:
#  Write a Python program to normalize a 3x3
# random matrix.

r3x3_matrix = np.random.random(9).reshape(3,3)
print(r3x3_matrix)
m_min,m_max = r3x3_matrix.min(),r3x3_matrix.max()
r3x3_matrix= (r3x3_matrix-m_min)/(m_max - m_min)
print(r3x3_matrix)

[[0.7711134  0.20480662 0.92347915]
 [0.93172791 0.00469707 0.92990391]
 [0.09028328 0.58220905 0.01993398]]
[[0.82674308 0.21586072 0.99110195]
 [1.         0.         0.99803242]
 [0.09232293 0.62296955 0.01643625]]


In [31]:
#  How to ignore all numpy warnings (not
# recommended)?

data = np.random.random(1000).reshape(10, 10,10)
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

array([0.4967398 , 0.49658271, 0.48506595, 0.49326182, 0.41365721,
       0.45919962, 0.57663164, 0.41761967, 0.43470346, 0.46690826])

In [43]:
#  How to swap two rows of an array?
import numpy as np
np_array = np.array([[1,2,3,4],[4,3,2,1],[3,4,5,6],[4,3,2,5]])
print(np_array)
np_array[[1,2]] = np_array[[2,1]]
print(np_array)


[[1 2 3 4]
 [4 3 2 1]
 [3 4 5 6]
 [4 3 2 5]]
[[1 2 3 4]
 [3 4 5 6]
 [4 3 2 1]
 [4 3 2 5]]


In [ ]:
 Compute bootstrapped 95% confidence
intervals for the mean of a 1D array X (i.e.,
resample the elements of an array with
replacement N times, compute the mean of
each sample, and then compute percentiles
over the means).

In [45]:
#  Python program to create a random vector of
# size 10 and sort it.

random_array = np.random.random(10)
print(random_array)
sort_array = np.sort(random_array)
print(sort_array)

[0.26475442 0.27806851 0.71348468 0.87066881 0.78942853 0.28645707
 0.54199401 0.82269204 0.76654743 0.06025203]
[0.06025203 0.26475442 0.27806851 0.28645707 0.54199401 0.71348468
 0.76654743 0.78942853 0.82269204 0.87066881]


In [50]:
#   Write a Python program to check two random
# arrays are equal or not.

random_array1 = np.random.random(20)
random_array2 = np.random.random(23)
print(random_array1)
print(random_array2)
print(np.array_equal(random_array1,random_array2))

[0.78128683 0.89586125 0.32240399 0.8817937  0.12887263 0.46015429
 0.86830701 0.5017858  0.63509734 0.61210004 0.46090966 0.02811338
 0.89067923 0.89743336 0.16989706 0.27625388 0.98564535 0.10879776
 0.89142173 0.54747887]
[0.664209   0.98767939 0.62735538 0.57310764 0.47789756 0.87212933
 0.12308512 0.50050497 0.0496165  0.21589424 0.53569392 0.86779252
 0.15031649 0.67465984 0.4626461  0.34225073 0.66863272 0.80352187
 0.09817628 0.69545232 0.50884022 0.4902907  0.25284496]
False


In [64]:
#  Write a Python program to add, subtract,
# multiply, divide arguments element-wise.
array1 = np.random.randint(1,10,24).reshape(3,2,4)
array2 = np.random.randint(1,10,24).reshape(3,2,4)
print(array1, '\n','_'*125, array2,'\n','_'*125)
print('Sum of array:','\n', array1 +array2,'_'*125)
print('Difference of array:','\n', array1 - array2,'_'*125)
print('Product of array:','\n', array1 * array2,'_'*125)
print('Quotient of array:','\n', array1 / array2,'_'*125)


[[[8 4 4 5]
  [6 7 6 1]]

 [[8 4 9 2]
  [4 6 2 8]]

 [[8 2 6 9]
  [5 9 1 9]]] 
 _____________________________________________________________________________________________________________________________ [[[4 7 9 9]
  [8 2 4 5]]

 [[5 3 2 1]
  [5 9 7 1]]

 [[5 4 3 1]
  [2 6 7 7]]] 
 _____________________________________________________________________________________________________________________________
Sum of array: 
 [[[12 11 13 14]
  [14  9 10  6]]

 [[13  7 11  3]
  [ 9 15  9  9]]

 [[13  6  9 10]
  [ 7 15  8 16]]] _____________________________________________________________________________________________________________________________
Difference of array: 
 [[[ 4 -3 -5 -4]
  [-2  5  2 -4]]

 [[ 3  1  7  1]
  [-1 -3 -5  7]]

 [[ 3 -2  3  8]
  [ 3  3 -6  2]]] _____________________________________________________________________________________________________________________________
Product of array: 
 [[[32 28 36 45]
  [48 14 24  5]]

 [[40 12 18  2]
  [20 54 14  8]]

 [[40

In [68]:
#  Write a Python program to get the dates of
# yesterday, today and tomorrow.
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-08-23
Today:  2022-08-24
Tomorrow:  2022-08-25
