### Numpy (Numerical Python) Library

In [ ]:
# NumPy, short for Numerical Python, has long been a cornerstone of numerical computing in Python. It provides the data
# structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python. 
# NumPy contains, among other things:

# ● A fast and efficient multidimensional array object ndarray
# ● Functions for performing element-wise computations with arrays or mathematical
# operations between arrays
# ● Tools for reading and writing array-based datasets to disk
# ● Linear algebra operations, Fourier transform, and random number generation
# ● A mature C API to enable Python extensions and native C or C++ code to access

In [ ]:
# NumPy’s data structures and computational facilities.

# Beyond the fast array-processing capabilities that NumPy adds to Python, one of its primary uses in data analysis is as a
# container for data to be passed between algorithms and libraries.

# For numerical data, NumPy arrays are more efficient for storing and manipulating data than the other built-in Python
# data structures. Also, libraries written in a lower-level language, such as C or Fortran, can operate on the data stored
# in a NumPy array without copying data into some other memory representation. Thus, many numerical computing tools for
# Python either assume NumPy arrays as a primary data structure or else target seamless interoperability with NumPy.

In [ ]:
# Why Numpy?
# One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on
# large arrays of data. There are a number of reasons for this:
# ● NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s
# library of algorithms written in the C language can operate on this memory without any type checking or other overhead. 
# NumPy arrays also use much less memory than built-in Python sequences.
# ● NumPy operations perform complex computations on entire arrays without the need for Python for loops. To give you an
# idea of the performance difference, consider a NumPy array of one million integers, and the equivalent Python list:

In [ ]:
import numpy as np
np.random.seed(42)

nump_a = np.arange(1000000)
list_a = list(range(1000000))

print(len(nump_a))

print(len(list_a))

In [ ]:
%%time

for x in range(10):
    nump_a2 = nump_a * 2

In [ ]:
%%time
for x in range(10):
    list_a2 = [x*2 for x in list_a]

In [ ]:
# The NumPy ndarray
# A Multidimensional Array Object One of the key features of NumPy is its N-dimensional array object, or ndarray, which is
# a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole
# blocks of data using similar syntax to the equivalent operations between scalar elements.

In [ ]:
data = np.random.randint(1,10,24).reshape(2,3,4)

print(data)

In [ ]:
data1 = np.random.randint(1,10,24)

print(data1)

In [ ]:
data2 = np.random.randint(1,10,24).reshape(4,6)
print(data2)

In [ ]:
# Note the appearance is of a 3 layer nested list. However, though they appear the same - these are arrays!! Important :
# note NO commas between the elements of the array. 

print(type(data))

for x in range(len(data)):
    for y in range(len(data[x])):
        for z in range(len(data[x][y])):
            print(data[x][y][z])
            
# The 3 dimensional array object is constructed of : 4 elements in each row, 3 rows nested in the 2nd dimension of the 
# array object and 2 such 2nd Dimension arrays nested in the outer most array block. 

In [ ]:
print(data)

In [ ]:
print(data * 10)

In [ ]:
# Note, we have not changed the original data ndarray.
print(data)

# We could change the original data variable by assigning the result to itself or to a new variable as usual.

In [ ]:
print(data+data)

In [ ]:
data1 = data*10

print(data1)

In [ ]:
data1 = data1+data1
print(data1)

In [ ]:
# An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same
# type. 

lst1 = ['a', 100, (20,30), {'x':10, 'y':20}]

np_arr = np.array(lst1)

In [ ]:
np_arr = np.array(lst1, dtype = int)

In [ ]:
# Unless explicitly specified, np.array tries to infer a good data type for the array that it creates.

In [ ]:
lst2 = [2.0, 300, 72, 3.4, 5.78]

np_arr = np.array(lst2)

In [ ]:
print(np_arr)
print(np_arr.dtype)

In [ ]:
lst3 = [2.13, 7.272, 3, 4.321, 11.234, 101]

np_arr2 = np.array(lst3)

print(np_arr2)
print(np_arr2.dtype)

print(type(np_arr2[2]))

In [ ]:
lst11 = [[1,2,3,4], [10,20,30,40]]

np_arr11 = np.array(lst11,dtype = int)

In [ ]:
np_arr = np.random.randint(2,4,24)
print(np_arr)

In [ ]:
np_arr_rs = np_arr.reshape(2,3,4)
print(np_arr_rs)

In [ ]:
# Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data
# type of the array:

print(data.shape)

In [ ]:
print(data.dtype)

In [ ]:
# Creating ndarrays The easiest way to create an array is to use the array function. This accepts any sequence-like object
# (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good
# candidate for conversion:

lst1 = [1,2,3,4]

nump_arr = np.array(lst1)

print(nump_arr)
print(type(nump_arr))
print(nump_arr.shape)
print(f'Dimensions of nump_arr is {nump_arr.ndim}.')

In [ ]:
# Note, how for a one dimensional array, the shape tuple is (4,) but the dimensions are 1.

In [ ]:
nump_arr = nump_arr.reshape(1,4)

print(nump_arr.shape)
print(nump_arr.ndim)
print(nump_arr)

In [ ]:
# Nested sequences, like a list of equal-length lists, will be converted into a multi-dimensional array:

In [ ]:
lst2 = [[1,2,3,4], [10,20,30,40]]

nump_arr2 = np.array(lst2)

print(nump_arr2)
print(type(nump_arr2))
print(nump_arr2.shape)
print(f'Dimensions of nump_arr2 is {nump_arr2.ndim}.')

In [ ]:
print(nump_arr2)
nump_arr2

In [ ]:
# Note the output when outputting nump_arr2 on the notebook. It specifies that this is an array - but note the return of the
# comma!! It doesnt make a difference since we know that this is an array but just pointing out the difference in the 
# view of both commands.

In [ ]:
#asarray

In [ ]:
import numpy as np

lst1 = [1,2,3,4]
np_array = np.array(lst1)
np_asarray = np.asarray(lst1)

print(np_array)
print(type(np_array))

print(np_asarray)
print(type(np_asarray))

In [ ]:
lst1[0] = 100

print(np_array)
print(np_asarray)

In [ ]:
np_array[0] = 100
print(np_array)
print(np_asarray)

In [ ]:
np_array[0] = 1
print(np_array)

In [ ]:
np_asarray[0] = 100
print(np_array)
print(np_asarray)


In [ ]:
lst2 = [[1,2,3,4], [100,200,300,400]]

np_lst = np.array(lst2)

In [ ]:
print(np_lst)

In [ ]:
np_array_lst = np.array(np_lst)
np_asarray_lst = np.asarray(np_lst)

print(np_array_lst)
print(np_asarray_lst)

In [ ]:
np_lst[0][0] = 1000

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

In [ ]:
np_array_lst = np.array()

In [2]:
# Before we go on - lets make the axis of Numpy clear. 
import numpy as np

arr = np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [4]:
arr1 = arr.reshape(3,8)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [5]:
arrx = np.arange(1,49)
arrx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [6]:
arr2 = arrx.reshape(2,3,8)
arr2    

array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]]])

In [8]:
arr2x = np.arange(1,49).reshape(2,2,4,3)

arr2x

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]],


       [[[25, 26, 27],
         [28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45],
         [46, 47, 48]]]])

In [ ]:
print('arr :', arr, '\n','_'*125)
print('arr1 :', arr1, '\n','_'*125)
print('arr2 :', arr2, '\n','_'*125)

In [ ]:
arr2 = arr.reshape(2,3,4)
arr3 = arr.reshape(2,4,3)
arr4 = arr.reshape(4,3,2)
print('arr2 :', arr2, '\n','_'*125)
print('arr3 :', arr3, '\n','_'*125)
print('arr4 :', arr4, '\n','_'*125)

In [ ]:
print(arr)

In [ ]:
print('Sum Arr', np.sum(arr, axis = 0)) # 1D Array has no axis 1.

In [ ]:
print(arr4)


In [ ]:
print(np.sum(arr4))

In [ ]:
print('sum Axis 0', np.sum(arr4, axis = 0))

In [ ]:
print(arr4)
print(arr4.shape)

In [ ]:
print(arr4)

In [ ]:
arr_col = np.sum(arr4, axis = 1)
print(arr_col)
print(arr_col.shape)

In [ ]:
print(arr4)

print('Sum Axis 2', np.sum(arr4, axis = 2))

In [ ]:
arr6 = np.arange(1,13).reshape(3,2,2)

print(arr6)

In [ ]:
arr = np.arange(1,49)
arr5 = arr.reshape(3,4,2,2)
print('arr5 :', arr5)
print('Sum Axis 3', np.sum(arr5, axis = 0))

In [ ]:
print(np.sum(arr6,axis = 2))

In [ ]:
print(np.sum(arr6, axis = 1))

In [ ]:
print(np.sum(arr6))

### Homogeneous n-dimensional vectors:

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape(using tuples for shape).

In [ ]:
np_zero = np.zeros(10)

print(np_zero)

In [ ]:
np_zero6x2 = np.zeros((2,6))

print(np_zero6x2)

In [ ]:
#Note above how the shape is a tuple. 

In [ ]:
np_one = np.ones(10)
print(np_one)

In [ ]:
np_one6x2 = np.ones((2,6))

print(np_one6x2)

In [ ]:
np_full_5 = np.full(10,5)

print(np_full_5)

In [ ]:
np_full_a = np.full(10, 'a')

In [ ]:
print(np_full_a)

In [ ]:
np_full6x2_5 = np.full((2,6), 5)

print(np_full6x2_5)

In [ ]:
# Empty creates an array without initializing its values to any particular value. To create a higher dimensional array
# with these methods, use a tuple for shape.

In [1]:
import numpy as np

np_empty = np.empty(10)
print(np_empty)

[2.12199579e-314 0.00000000e+000 2.12199579e-314 4.94065646e-324
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000]


In [2]:
np_empty6x2 = np.empty((2,6))
print(np_empty6x2)

[[9.95834950e-312 9.95834951e-312 9.95834950e-312 0.00000000e+000
  3.14573993e+097 9.95219310e-312]
 [0.00000000e+000 7.41098469e-323 4.46919854e-310 6.95222800e-310
  0.00000000e+000 7.41098469e-323]]


In [ ]:
#Note that the numpy empty does not actually have empty values - it does create the array of desired shape and size but with
# arbitary values. It is slightly faster to initialise than np.zeros and np.ones especially for larger arrays. 

#### Note that for each of np.zeros, np.ones, np.full and np.empty there are np.zeros_like, ones_like, full_like and empty_like which behave just like the difference between np.array and np.asarray i.e. if the matrix is already an array, then does not create a copy but just gives array like funcitonality.

In [ ]:
#Matrix Functions

In [3]:
#1. The identity matrix:
# In linear algebra, the identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros
# elsewhere.

np_id = np.identity(5)

print(np_id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Note that by default the 1s and 0s are float type. 

In [4]:
np_id_int = np.identity(5, dtype = int)

print(np_id_int)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
np_id_bool = np.identity(5,dtype= bool)

print(np_id_bool)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [7]:
# 2. Function ‘eye’:
# It is used to return a 2-D array with ones on the diagonal and zeros elsewhere. Unlike identity, array does not necessarily
# have to be square.

np_eye_1 = np.eye(5)

print(np_eye_1)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
np_eye_5x4 = np.eye(5,4)

print(np_eye_5x4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
# We can also specify the diagnol in the eye function unlike the identity function. 0 is the default, Positive values are
# integers above the main diagonal and negative values are integers below the main diagonal. 

In [15]:
np_eye_8x6_0 = np.eye(6,6,0)

print(np_eye_8x6_0)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [16]:
np_eye_8x6_p1 = np.eye(6,6,1)

print(np_eye_8x6_p1)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
np_eye_8x6_p2 = np.eye(6,6,2)

print(np_eye_8x6_p2)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
np_eye_8x6_n1 = np.eye(6,6,-1)

print(np_eye_8x6_n1)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [26]:
np_eye_8x6_n2 = np.eye(6,6,00)

print(np_eye_8x6_n2)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# 3. Function diag:
# The diag function takes two arguments:
# ● An ndarray v.
# ● An integer k (default = 0). If ‘v’ is dimension is 1 then the function constructs a matrix where its diagonal number k 
# is formed by the elements of the vector ‘v’. If a is a matrix (dimension 2) then the function extracts the elements of
# the kth diagonal in a one-dimensional vector.

In [27]:
np_diag = np.diag([1,5,7])

print(np_diag)

[[1 0 0]
 [0 5 0]
 [0 0 7]]


In [ ]:
np_array_1 = np.ones((3,3))*5

np_diag1 = np.diag(np_array_1)

np_array_1 = np.diag([1,3,5])

In [30]:
np_diag1 = np.diag(np_array_1)

print(np_array_1)

[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [31]:
print(np_diag1)

[1 3 5]


In [32]:
np_arr_lst = np.array([[1,2,3], [10,20,30], [100,200,300]])

print(np_arr_lst)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [33]:
np_diag_l = np.diag(np_arr_lst)

print(np_diag_l)

[  1  20 300]


In [ ]:
np_diag_2 = np.diag(np_arr_lst, 1)

print(np_diag_2)

In [35]:
# 4. Function ‘fromfunction’:
# Construct an array by executing a function over each coordinate. Let’s create a vector-based on its indices.

np_ffunc = np.fromfunction(lambda x,y,z : x-y+z, (3,3,3))

print(np_ffunc)

[[[ 0.  1.  2.]
  [-1.  0.  1.]
  [-2. -1.  0.]]

 [[ 1.  2.  3.]
  [ 0.  1.  2.]
  [-1.  0.  1.]]

 [[ 2.  3.  4.]
  [ 1.  2.  3.]
  [ 0.  1.  2.]]]


In [ ]:
#Remember here that the co-ordinates x,y for each element are as follows:

0,0   0,1   0,2
1,0   1,1   1,2
2,0   2,1   2,2

In [ ]:
np_ffuncXY2 = np.fromfunction(lambda x,y : x*y+2, (3,3))

print(np_ffuncXY2)

0,0,0  0,0,1  0,0,2
0,1,0  0,1,1, 0,1,2
0,2,0, 0,2,1, 0,2,2

1,0,0  0,0,1  0,0,2
1,1,0  0,1,1, 0,1,2
1,2,0, 0,2,1, 0,2,2

2,0,0  0,0,1  0,0,2
2,1,0  0,1,1, 0,1,2
2,2,0, 0,2,1, 0,2,2

In [36]:
import numpy as np

np_ffunct_gte = np.fromfunction(lambda x,y : x >= y, (3,3))

print(np_ffunct_gte)

[[ True False False]
 [ True  True False]
 [ True  True  True]]


In [37]:
# Aggregation methods:

np_sample = np.arange(24).reshape(2,3,4)

print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [38]:
test = list(range(1,20,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [39]:
test1 = np.arange(1,5,0.2)

print(test1)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]


In [41]:
# ● ndarray.sum: Return the sum of the array elements over the given axis.
print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
print(np_sample.sum()) # - With no axis specified, sums all the elements of the 0 axis.

276


In [43]:
np_s_a0 = np_sample.sum(0) # - with axis specified sums elements of specified axis or you could say collapses specified axis

print(np_s_a0)
print(np_s_a0.ndim)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
2


In [44]:
print(np_sample)
print(np_sample.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [45]:
np_s_a1 = np_sample.sum(1)

print(np_s_a1)
print(np_s_a1.ndim)

[[12 15 18 21]
 [48 51 54 57]]
2


In [46]:
np_s_a2 = np_sample.sum(2)

print(np_s_a2)
print(np_s_a2.ndim)

[[ 6 22 38]
 [54 70 86]]
2


In [47]:
print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [48]:
# ● ndarray.product: Return the product of the array elements over the given axis.

np_sample_2 = np.arange(1,11).reshape(2,5)

print(np_sample_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [49]:
np_prod = np_sample_2.prod()

print(np_prod)

3628800


In [50]:
print(np_sample_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [51]:
np_prod_0 = np_sample_2.prod(0)

print(np_prod_0)

[ 6 14 24 36 50]


In [52]:
np_prod_1 = np_sample_2.prod(1)

print(np_prod_1)

[  120 30240]


In [53]:
np_rand_sample = np.random.randint(1,100,24).reshape(2,3,4)

print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [ ]:
# ● ndarray.max: Return the maximum along the given axis.
# ● ndarray.argmax: Return indices of the maximum values along the given axis

In [54]:
print(np_rand_sample.max()) #without any axis - maximum of array

print(np_rand_sample.argmax()) # Index position of maximum number - without any axis > index value of max number (flattened
# array)

print(np_rand_sample.flatten())

94
14
[54  1 78  6  9 60  6 33 90 27 90 83 62 78 94 76 77 79 48  8 11 77 42 41]


In [56]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [55]:
print(np_rand_sample.max(0)) # with axis 0

print(np_rand_sample.argmax(0)) # with axis 0

[[62 78 94 76]
 [77 79 48 33]
 [90 77 90 83]]
[[1 1 1 1]
 [1 1 1 0]
 [0 1 0 0]]


In [57]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [58]:
print(np_rand_sample.max(1))
print(np_rand_sample.argmax(1))


[[90 60 90 83]
 [77 79 94 76]]
[[2 1 2 2]
 [1 1 0 0]]


In [59]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [60]:
print(np_rand_sample.max(2))
print(np_rand_sample.argmax(2))

[[78 60 90]
 [94 79 77]]
[[2 1 0]
 [2 1 1]]


In [61]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [ ]:
# ● ndarray.min: Return the minimum along the given axis.
# ● ndarray.argmin: Return indices of the minimum values along the given axis.

In [62]:
print(np_rand_sample.min())
print(np_rand_sample.argmin())
print(np_rand_sample.flatten())

1
1
[54  1 78  6  9 60  6 33 90 27 90 83 62 78 94 76 77 79 48  8 11 77 42 41]


In [63]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [64]:
print(np_rand_sample.min(0))
print(np_rand_sample.argmin(0))

[[54  1 78  6]
 [ 9 60  6  8]
 [11 27 42 41]]
[[0 0 0 0]
 [0 0 0 1]
 [1 0 1 1]]


In [65]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [66]:
print(np_rand_sample.min(1))
print(np_rand_sample.argmin(1))

[[ 9  1  6  6]
 [11 77 42  8]]
[[1 0 1 0]
 [2 2 2 1]]


In [67]:
print(np_rand_sample.min(2))
print(np_rand_sample.argmin(2))

[[ 1  6 27]
 [62  8 11]]
[[1 2 1]
 [0 3 0]]


In [68]:
# ● ndarray.mean: Returns the average of the array elements along the given axis.

print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [69]:
print(np_rand_sample.mean()) #without axis - mean of all elements.

51.25


In [70]:
print(np_rand_sample.mean(0))

[[58.  39.5 86.  41. ]
 [43.  69.5 27.  20.5]
 [50.5 52.  66.  62. ]]


In [71]:
print(np_rand_sample.mean(1))

[[51.         29.33333333 58.         40.66666667]
 [50.         78.         61.33333333 41.66666667]]


In [72]:
print(np_rand_sample.mean(2))

[[34.75 27.   72.5 ]
 [77.5  53.   42.75]]


In [ ]:
# ● ndarray.cumsum: Return the cumulative sum of the elements along the given axis.

In [73]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [74]:
print(np_rand_sample.cumsum())

[  54   55  133  139  148  208  214  247  337  364  454  537  599  677
  771  847  924 1003 1051 1059 1070 1147 1189 1230]


In [75]:
print(np_rand_sample.cumsum(0))

[[[ 54   1  78   6]
  [  9  60   6  33]
  [ 90  27  90  83]]

 [[116  79 172  82]
  [ 86 139  54  41]
  [101 104 132 124]]]


In [76]:
print(np_rand_sample.cumsum(1))

[[[ 54   1  78   6]
  [ 63  61  84  39]
  [153  88 174 122]]

 [[ 62  78  94  76]
  [139 157 142  84]
  [150 234 184 125]]]


In [77]:
print(np_rand_sample.cumsum(2))

[[[ 54  55 133 139]
  [  9  69  75 108]
  [ 90 117 207 290]]

 [[ 62 140 234 310]
  [ 77 156 204 212]
  [ 11  88 130 171]]]


In [ ]:
# ● ndarray.cumprod: Return the cumulative product of the elements along the given axis.

In [78]:
np_sample_cd = np.random.randint(1,10, 12).reshape(2,2,3)

print(np_sample_cd)

[[[4 5 7]
  [4 4 1]]

 [[6 9 8]
  [6 6 1]]]


In [79]:
print(np_sample_cd.cumprod())

[       4       20      140      560     2240     2240    13440   120960
   967680  5806080 34836480 34836480]


In [80]:
print(np_sample_cd.cumprod(0))

[[[ 4  5  7]
  [ 4  4  1]]

 [[24 45 56]
  [24 24  1]]]


In [81]:
print(np_sample_cd)

[[[4 5 7]
  [4 4 1]]

 [[6 9 8]
  [6 6 1]]]


In [82]:
print(np_sample_cd.cumprod(1))

[[[ 4  5  7]
  [16 20  7]]

 [[ 6  9  8]
  [36 54  8]]]


In [83]:
print(np_sample_cd.cumprod(2))

[[[  4  20 140]
  [  4  16  16]]

 [[  6  54 432]
  [  6  36  36]]]


In [ ]:
# ● ndarray.var: Returns the variance of the array elements, along the given axis.
# ● ndarray.std: Returns the standard deviation of the array elements along the given axis.

In [85]:
print(np_rand_sample)

[[[54  1 78  6]
  [ 9 60  6 33]
  [90 27 90 83]]

 [[62 78 94 76]
  [77 79 48  8]
  [11 77 42 41]]]


In [84]:
print('Variance : ', np_rand_sample.var())
print('Standard Deviation : ', np_rand_sample.std())

Variance :  966.5208333333334
Standard Deviation :  31.08891817566725


In [86]:
print('Variance')
print(np_rand_sample.var(0))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(0))

Variance
[[  16.   1482.25   64.   1225.  ]
 [1156.     90.25  441.    156.25]
 [1560.25  625.    576.    441.  ]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[ 4.  38.5  8.  35. ]
 [34.   9.5 21.  12.5]
 [39.5 25.  24.  21. ]]


In [87]:
print('Variance')
print(np_rand_sample.var(1))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(1))

Variance
[[1.09800000e+03 5.82888889e+02 1.37600000e+03 1.01755556e+03]
 [7.98000000e+02 6.66666667e-01 5.39555556e+02 7.70888889e+02]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[33.13608305 24.14309195 37.09447398 31.89914663]
 [28.24889378  0.81649658 23.22833519 27.7648859 ]]


In [88]:
print('Variance')
print(np_rand_sample.var(2))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(2))

Variance
[[1051.6875  472.5     698.25  ]
 [ 128.75    825.5     546.1875]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[32.42973173 21.73706512 26.42442052]
 [11.34680572 28.7315158  23.37065468]]


### Data Types for ndarrays

In [ ]:
# The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to
# interpret a chunk of memory as a particular type of data:

In [89]:
import numpy as np
import sys
np_arr1 = np.array([1,2,3], dtype = 'float16')

In [90]:
print(np_arr1.dtype)
print(np_arr1)

float16
[1. 2. 3.]


In [91]:
np_arr2 = np.array([10,-4,3], dtype = 'int8')

print(np_arr2.dtype)
print(np_arr2)

print(sys.getsizeof(np_arr2[0]))
print(sys.getsizeof(10))

int8
[10 -4  3]
25
28


In [ ]:
# Type              Type code           Description
# int8, uint8       i1, u1              Signed and unsigned 8-bit (1byte) integer types
# int16, uint16     i2, u2              Signed and unsigned 16-bit integer types
# int32, uint32     i4, u4              Signed and unsigned 32-bit integer types
# int64, uint64     i8, u8              Signed and unsigned 64-bit integer types
# float16           f2                  Half-precision floating point
# float32           f4 or f             Standard single-precision floating point; compatible with C float
# float64           f8 or d             Standard double-precision floating point; compatible with C double
#                                       and Python float object
# float128          f16 or g            Extended-precision floating point
# complex64,        c8, c16, c32        Complex numbers represented by two 32, 64, or 128 floats respectively
# complex128,
# complex256
# bool              ?                   Boolean type storing True and False values
# object            O                   Python object type; a value can be any Python object
# string_           S                   Fixed-length ASCII string type (1 byte per character); for example, to create a
#                                       string dtype with length 10, use 'S10'
# unicode_          U                   Fixed-length Unicode type (number of bytes platform specific); same specification
#                                       semantics as string_ (e.g., 'U10')

# Note: It’s important to be cautious when using the numpy string_ type, as string data in NumPy is fixed size and may
# truncate input without warning

### Arithmetic with NumPy

In [ ]:
# Arrays Arrays are important because they enable you to express batch operations on data without writing any for loops. 
# NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation
# element-wise:

In [92]:
np_arr1 = np.array([[1,2,3], [4,5,6]])

np_arr2 = np.array([[2,4,6], [8,10,12]])

print(np_arr1)
print(np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [93]:
print(np_arr1 * np_arr2)

[[ 2  8 18]
 [32 50 72]]


In [94]:
print(np_arr2 - np_arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [96]:
print(np_arr1)

[[1 2 3]
 [4 5 6]]


In [110]:
print(1/(np_arr1**2))

[[1.         0.25       0.11111111]
 [0.0625     0.04       0.02777778]]


In [ ]:
print(np_arr1)
print(np_arr2)

In [99]:
print(np_arr1 * np_arr2)

[[ 2  8 18]
 [32 50 72]]


In [104]:
print((np_arr1*np_arr2)**1/2)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [ ]:
# Comparisons between arrays of the same size yield boolean arrays:

In [102]:
print(np_arr1)
print(np_arr2)

print(np_arr1 < np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[ True  True  True]
 [ True  True  True]]


In [14]:
arrtest = np.arange(1,11).reshape(2,5)

arrtest

print(arrtest.ndim)
print(arrtest)

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
# Uncommon dimensions arrays are 'broadcast'. E.g.

import numpy as np

# However, broadcasting needs to follow certain rules. 

# Arrays are broadcastable if:

# Arrays have exactly the same shape.

np_arr_so = np.arange(1,7).reshape(3,2)
np_arr_lo = np.arange(10,70,10).reshape(3,2)

print(np_arr_so)
print(np_arr_lo)

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]


In [16]:
print(np_arr_so*np_arr_lo)

[[ 10  40]
 [ 90 160]
 [250 360]]


In [19]:
# Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

np_arr_so = np.arange(3).reshape(1,3)
print(np_arr_so)

[[0 1 2]]


In [20]:
np_arr_lo = np.arange(0,60,10).reshape(2,3)
print(np_arr_lo)

[[ 0 10 20]
 [30 40 50]]


In [21]:
print(np_arr_so*np_arr_lo)

[[  0  10  40]
 [  0  40 100]]


In [36]:
arr_lo = np.arange(1,385).reshape(2,4,6,8)
arr_so = np.arange(1,17).reshape(2,1,1,8)

print(arr_lo * arr_so)

[[[[   1    4    9   16   25   36   49   64]
   [   9   20   33   48   65   84  105  128]
   [  17   36   57   80  105  132  161  192]
   [  25   52   81  112  145  180  217  256]
   [  33   68  105  144  185  228  273  320]
   [  41   84  129  176  225  276  329  384]]

  [[  49  100  153  208  265  324  385  448]
   [  57  116  177  240  305  372  441  512]
   [  65  132  201  272  345  420  497  576]
   [  73  148  225  304  385  468  553  640]
   [  81  164  249  336  425  516  609  704]
   [  89  180  273  368  465  564  665  768]]

  [[  97  196  297  400  505  612  721  832]
   [ 105  212  321  432  545  660  777  896]
   [ 113  228  345  464  585  708  833  960]
   [ 121  244  369  496  625  756  889 1024]
   [ 129  260  393  528  665  804  945 1088]
   [ 137  276  417  560  705  852 1001 1152]]

  [[ 145  292  441  592  745  900 1057 1216]
   [ 153  308  465  624  785  948 1113 1280]
   [ 161  324  489  656  825  996 1169 1344]
   [ 169  340  513  688  865 1044 1225 1408]
   [

In [37]:
np_arr_lo = np.arange(0,60,10).reshape(3,2)
np_arr_so = np.arange(2).reshape(1,2)

print(np_arr_lo)
print(np_arr_so)

[[ 0 10]
 [20 30]
 [40 50]]
[[0 1]]


In [38]:
print(np_arr_lo*np_arr_so)

[[ 0 10]
 [ 0 30]
 [ 0 50]]


In [39]:
np_arr_so = np.arange(6).reshape(1,2,3)
np_arr_so

array([[[0, 1, 2],
        [3, 4, 5]]])

In [40]:
np_arr_lo = np.arange(0,120,10).reshape(2,2,3)
np_arr_lo

array([[[  0,  10,  20],
        [ 30,  40,  50]],

       [[ 60,  70,  80],
        [ 90, 100, 110]]])

In [41]:
print(np_arr_so+np_arr_lo)

[[[  0  11  22]
  [ 33  44  55]]

 [[ 60  71  82]
  [ 93 104 115]]]


In [60]:
# Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated
# property is true.

np_arr_so = np.arange(1,7).reshape(1,2,3)
print(np_arr_so)

[[[1 2 3]
  [4 5 6]]]


In [61]:
np_arr_lo = np.arange(1,19).reshape(3,2,3)
print(np_arr_lo)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [62]:
np_arr_so*np_arr_lo

array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [63]:
np_arr_so = np_arr_so.reshape(1,2,3)
print(np_arr_so)

[[[1 2 3]
  [4 5 6]]]


In [56]:
print(np_arr_so*np_arr_lo)

[[[  1   4   9]
  [ 16  25  36]]

 [[  7  16  27]
  [ 40  55  72]]

 [[ 13  28  45]
  [ 64  85 108]]]


In [ ]:
# However, broadcasting follows certain rules:

# Array with smaller ndim than the other is prepended with '1' in its shape.

# Size in each dimension of the output shape is maximum of the input sizes in that dimension.

# An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly
# 1.

# If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that
# dimension.

### Basic Indexing and Slicing

In [ ]:
#NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual
# elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [64]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
print(arr1[5])

5


In [66]:
print(arr1[2:4])

[2 3]


In [67]:
# Slice assignment

arr1[2:4] = 11

print(arr1)

[ 0  1 11 11  4  5  6  7  8  9]


In [68]:
list1 = list(range(10))
print(list1)
list1[2:4] = 11,
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 11, 4, 5, 6, 7, 8, 9]


In [87]:
# As you can see, if you assign a scalar value to a slice of an array, as in arr[2:4] = 11, the value is propagated (or 
# broadcasted henceforth) to the entire selection. While for lists, the value(s) of the iterable replace(s) the slice.

In [ ]:
# An important first distinction from Python’s built-in lists is that array slices are views on the original array. This
# means that the data is not copied, and any modifications to the view will be reflected in the source array. To give
# an example of this, first create a slice of arr:

In [69]:
arr = np.arange(11)
arr_slice = arr[5:8]
print(arr_slice)

[5 6 7]


In [70]:
arr_slice[1] = 6789
print(arr_slice)
print(arr)

[   5 6789    7]
[   0    1    2    3    4    5 6789    7    8    9   10]


In [71]:
list1 = list(range(11))
lst_slice = list1[5:8]
print(lst_slice)

[5, 6, 7]


In [72]:
lst_slice[1] = 6789
print(lst_slice)
print(list1)

[5, 6789, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# To copy an array or its slice you have to exlicitly copy.

In [73]:
arr = np.arange(11)
print(arr)
arr_slice = arr[5:8].copy()

print(arr_slice)

[ 0  1  2  3  4  5  6  7  8  9 10]
[5 6 7]


In [74]:
arr_slice[1] = 6789

print(arr_slice)
print(arr)

[   5 6789    7]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [98]:
# Accessing values in nested arrays.

In [75]:
arr_hdim = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr_hdim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [101]:
print(arr_hdim[1][1])

5


In [76]:
# Numpy allows you to use easier syntax to access elements in nested arrays.

print(arr_hdim[1,0])

4


In [78]:
#Indexing with slices

#Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:

arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
print(arr[1:6])

[1 2 3 4 5]


In [80]:
# Consider a two-dimensional array. Slicing this array is a bit different:
 
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
print(arr_2d[:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
# As we see, the array has been sliced on axis 0

In [82]:
# As the syntax for multiple indexes seen previously, we can pass multiple slices as well. 

print(arr_2d[:2])
print(arr_2d[:2, :2])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [84]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
# or

print(arr_2d[:2,1:])

[[2 3]
 [5 6]]


In [ ]:
# When slicing like this, you always obtain array views of the same number of dimensions

In [ ]:
# By mixing integer indexes and slices, you get lower dimensional slices

In [86]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
print(arr_2d[1,1:])

[5 6]


In [ ]:
# Here we first selected the 1st index on axis 0 and then sliced from 1st index to end along axis 1

In [88]:
# Another example, slice from 1st index to end along axis 0 and then index 2 along axis 1
print(arr_2d[1:])

print(arr_2d[1:,2])

[[4 5 6]
 [7 8 9]]
[6 9]


### Boolean Indexing

In [ ]:
# Let’s consider an example where we have some data in an array and an array of names with duplicates. 

In [89]:
names = np.array(['Bob', 'John', 'Steve', 'Will', 'Bob', 'Steve', 'Bob'])
print(names)

['Bob' 'John' 'Steve' 'Will' 'Bob' 'Steve' 'Bob']


In [90]:
# Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with
# the string 'Bob' yields a boolean array:
print(names == 'Bob')

[ True False False False  True False  True]


In [91]:
data = np.random.randint(1,10,49).reshape(7,7)

print(data)

[[8 9 1 7 2 6 1]
 [5 4 7 2 8 5 6]
 [7 2 7 1 8 5 8]
 [8 6 6 1 7 3 9]
 [3 4 6 4 8 6 9]
 [3 5 9 7 9 5 9]
 [8 9 2 3 6 3 1]]


In [ ]:
# We can use the values from the boolean array returned from the comparison operator == performed on 'names' array to 
# index from another array data.

In [ ]:
print(names=='Bob')

In [92]:
print(data[1, names == 'Bob'])

[ True False False False  True False  True]
[5 8 6]


In [93]:
print(data[names == 'Bob'])

[[8 9 1 7 2 6 1]
 [3 4 6 4 8 6 9]
 [8 9 2 3 6 3 1]]


In [97]:
print(data[names == 'Bob', names=='Bob'])

[8 8 1]


In [95]:
# Arange function in Numpy. Takes 4 arguments

#1. Start - Optional - defaults to 0
#2. Stop - Mandatory
#3. Step - Optional - Defaults to 1 but can take floating point numbers as a step (Unlike built-in range function of Python)
#4. dtype - Optional


np_arr_dec = np.arange(1,3,0.1)

print(np_arr_dec)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9]


In [98]:
range_1 = list(range(1,3,0.1))
print(list(range_1))

TypeError: 'float' object cannot be interpreted as an integer

In [99]:
range_2 = list(range(1,3,1))
print(list(range_2))

[1, 2]


In [ ]:
# linspace function - returns evenly spaced equidistant number numbers between a specified range.

In [ ]:
# It takes 7 arguments.

#1. Start - Mandatory
#2. Stop - Mandatory
#3. Num - Optional - Number of samples required between the range/interval. By default set to 50
#4. endpoint - Optional - By default set to true and includes the endpoint(i.e. stop value) - if set to False, returns
# equidistant numbers not including the endpoint/stop value.
#5 retstep - Optional - Default is False. If set to true, returns the samples and the step value (distance between samples)
#6 dtype - Optional - By default datatype will be inferred. However, for int datatype, float will be considered even if 
# start and stop are int.
#7 axis - Optional - By default 0 axis. Only useful in case start and stop are array-like.



In [100]:
arr_lin = np.linspace(1,10)

print(arr_lin)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [ ]:
# By default creates 50 equidistant samples / points

In [101]:
arr_lin10 = np.linspace(1,20,5) # with num of samples specified

print(arr_lin10)

[ 1.    5.75 10.5  15.25 20.  ]


In [102]:
arr_lin10_noEP = np.linspace(1,20,5, endpoint=False) #No Endpoint included

In [103]:
print(arr_lin10_noEP)

[ 1.   4.8  8.6 12.4 16.2]


In [104]:
arr_lin10_noEP_wRS = np.linspace(1,20,5, endpoint=False, retstep=True) #With array as 1st element and step value as 2nd
                                                                       # element of tuple.
print(arr_lin10_noEP_wRS)
print(type(arr_lin10_noEP_wRS))

(array([ 1. ,  4.8,  8.6, 12.4, 16.2]), 3.8)
<class 'tuple'>


In [105]:
arr_lin10_int = np.linspace(1,20,5, dtype = int) # With dtype specified.
print(arr_lin10_int)

[ 1  5 10 15 20]


In [106]:
arr_like_lin10 = np.linspace((1,2), (3,4), 10) # Array like start and stop values.
print(arr_like_lin10)

#Note here that default axis is 0. The equidistant numbers are being added along 0 axis

[[1.         2.        ]
 [1.22222222 2.22222222]
 [1.44444444 2.44444444]
 [1.66666667 2.66666667]
 [1.88888889 2.88888889]
 [2.11111111 3.11111111]
 [2.33333333 3.33333333]
 [2.55555556 3.55555556]
 [2.77777778 3.77777778]
 [3.         4.        ]]


In [107]:
arr_like_lin10_ax1 = np.linspace((1,2), (3,4), 10, axis=1) # with equidistant samples added along axis 1

print(arr_like_lin10_ax1)

[[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
  2.33333333 2.55555556 2.77777778 3.        ]
 [2.         2.22222222 2.44444444 2.66666667 2.88888889 3.11111111
  3.33333333 3.55555556 3.77777778 4.        ]]


### Random Module in Numpy

In [108]:
#Randint to generate a random integer

result = np.random.randint(1,10,5)

print(result)

# Returns random numbers between specified range and number of values specified in third parameter

[9 6 9 3 4]


In [110]:
print(np.random.randint(1,10)) # Prints 1 number between 0 and 9 - Start not specified defaults to 0, number not specified 
                             # defaults to 1.

6


In [111]:
#rand - For random float values between 0 and 1 only.

result = np.random.rand()

print(result)



0.29958818329062964


In [114]:
print(np.random.rand(3,2,4)) # Can take shape as parameter. Here will return 3 arrays on axis 0, 2 on 1 and 4 on 2

[[[0.80763047 0.8891886  0.33722091 0.49226925]
  [0.62312287 0.90830988 0.81359629 0.9749045 ]]

 [[0.94607249 0.07333005 0.54182703 0.42273156]
  [0.03507878 0.84067915 0.90576051 0.58613185]]

 [[0.99908423 0.8297706  0.45218483 0.64039608]
  [0.00660717 0.60058915 0.51510622 0.2899493 ]]]


In [115]:
#randn function - returns float values in given shape array from a standard normal distribution i.e. 

# Roughly - 65% of the values will be between -1 to 1
# Roughly - 95% of the values will be between -2 to 2
# Roughly - 99% of the values will be between -3 to 3

# If no shape provided will return a single float value.

result = np.random.randn(3,3,3)

print(result)

[[[ 0.43236398  0.27173714 -0.3516392 ]
  [ 0.4341179   0.03792527  0.87209585]
  [-1.0459183   0.03908669  0.66462932]]

 [[ 0.99509514 -0.87215006  0.36055482]
  [ 2.52223985  0.76750303  0.29104918]
  [ 0.71888193  0.13484884  0.22235601]]

 [[-0.12877236  0.29460654 -0.08521277]
  [-0.38389907  0.60340514 -0.80798834]
  [ 0.04931206 -0.87575311  0.7782459 ]]]


In [119]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
#choice - Choose a random number from an array or integer. 

# Takes only one 1D array or an integer as input from which to chose. 

choice = np.random.choice(arr1)

print(choice)

6


In [121]:
choice = np.random.choice(10) # If an integer x is specified - treats it as a choice in np.arange(x) i.e from 0 to x-1 e.g.
                              # here - it will choose between 0 to 9.
    
print(choice)

1


In [123]:
choice = np.random.choice(arr1, 5) # Size of choice specified.
print(choice)

[2 3 6 2 8]


In [127]:
# By default - replace parameter is True i.e. if a number has been chosen, it will be put back in the array and has a chance
# to be chosen again. By setting to false - the number is removed from array and wont be chosen again.

choice = np.random.choice(arr1, 10, replace = False)

print(choice)

[4 1 9 6 0 2 5 7 3 8]


In [131]:
# The p parameter takes probabilities i.e. if I had numbers 1 to 5 - in a uniform distribution each would have a 20% chance
# or (0.2 probability). However, if we were to specify the probabilities, it will take those probabilities into account
# while generating random numbers

choice = np.random.choice(np.arange(3), p = [0.1,0.2,0.7], size = 10)

print(choice)

[2 2 2 1 2 1 2 2 0 2]


In [132]:
#permutation - Returns a random permutation of input array or if integer specified random permutation of np.arrange(integer)

perm = np.random.permutation(10)

print(perm)

[7 4 1 5 9 8 0 2 6 3]


In [133]:
arr = np.arange(24).reshape(4,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [134]:
perm_arr = np.random.permutation(arr) #
print(perm_arr)


# For a multidimensional array - it is only shuffled along the 0 index axis.

[[[18 19]
  [20 21]
  [22 23]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[12 13]
  [14 15]
  [16 17]]]


In [135]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#any - Returns true if any of the elements in the array are true. 
#all Returns true if all of the elements in the array are true.

In [136]:
print(np.any(arr))
print(np.all(arr))

True
False


In [137]:
arr_zero = np.zeros(5)

print(np.any(arr_zero))
print(np.all(arr_zero))

False
False


In [138]:
arr_alt = np.random.randint(0,2,5)

print(arr_alt)

[0 0 1 1 0]


In [139]:
print(np.any(arr_alt))
print(np.all(arr_alt))

True
False


In [140]:
arr_zero_grid = np.zeros((2,3))

print(np.any(arr_zero_grid))
print(np.all(arr_zero_grid))

False
False


In [141]:
arr_one_grid = np.ones((2,3))
print(arr_one_grid)
print(np.any(arr_one_grid))
print(np.all(arr_one_grid))

[[1. 1. 1.]
 [1. 1. 1.]]
True
True


In [143]:
arr = np.arange(11)
arr10 = np.arange(11,21)
print(arr)
print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [144]:
# Append

arr_n_10 = np.append(arr, arr10)
print(arr_n_10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [145]:
arr_1 = np.arange(1,11).reshape(2,5)
arr_2 = np.arange(21,31).reshape(2,5)

print(arr_1)
print(arr_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[21 22 23 24 25]
 [26 27 28 29 30]]


In [146]:
arr_1n2 = np.append(arr_1, arr_2, axis = 1)

print(arr_1n2)

[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]]


In [147]:
arr_1n2V = np.append(arr_1, arr_2, axis = 0)

print(arr_1n2V)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [148]:
#vstack - stacks arrays vertically

arr_V = np.vstack((arr_1, arr_2))
print(arr_V)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [150]:
arr1x = np.arange(1,6)
arr2x = np.arange(11,16)
print(arr1x)
print(arr2x)

[1 2 3 4 5]
[11 12 13 14 15]


In [155]:
arr_vx = np.vstack((arr1x, arr2x))
arr_vx


array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [158]:
arr_apx = np.append(arr1x, arr2x, axis = 1)

arr_apx

AxisError: axis 1 is out of bounds for array of dimension 1

In [153]:
arr_H = np.hstack((arr1x, arr2x))

print(arr_H)

[ 1  2  3  4  5 11 12 13 14 15]


In [159]:
#sort

arr_rand = np.random.randint(1,10, 20).reshape(4,5)
print(arr_rand)

[[8 9 7 8 7]
 [8 6 5 6 9]
 [6 6 3 8 5]
 [3 6 4 7 5]]


In [160]:
arr_sort = np.sort(arr_rand)
print(arr_sort)

[[7 7 8 8 9]
 [5 6 6 8 9]
 [3 5 6 6 8]
 [3 4 5 6 7]]


In [162]:
print(arr_rand)
arr_sort = np.sort(arr_rand, axis = 0)
print(arr_sort)

[[8 9 7 8 7]
 [8 6 5 6 9]
 [6 6 3 8 5]
 [3 6 4 7 5]]
[[3 6 3 6 5]
 [6 6 4 7 5]
 [8 6 5 8 7]
 [8 9 7 8 9]]


In [165]:
# insert

print(arr_sort)

[[3 6 3 6 5]
 [6 6 4 7 5]
 [8 6 5 8 7]
 [8 9 7 8 9]]


In [166]:
arr_ins = np.insert(arr_sort, 15, [0,0,0,0,0]).reshape(5,5)

print(arr_ins)

[[3 6 3 6 5]
 [6 6 4 7 5]
 [8 6 5 8 7]
 [0 0 0 0 0]
 [8 9 7 8 9]]


In [167]:
arr_flat = arr_ins.flatten()
print(arr_flat)

[3 6 3 6 5 6 6 4 7 5 8 6 5 8 7 0 0 0 0 0 8 9 7 8 9]


In [168]:
arr_flat_ins = np.insert(arr_flat, 4, 20)

print(arr_flat_ins)

[ 3  6  3  6 20  5  6  6  4  7  5  8  6  5  8  7  0  0  0  0  0  8  9  7
  8  9]


In [ ]:
#Transpose

In [177]:
arr_1 = np.arange(1,25).reshape(4,6)

arr_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [178]:
arr_2 = arr_1.transpose() #Returns only a view of the transposed array and does not have a inplace parameter - so to see
# the effect - must save the transposed view to a variable.

arr_2

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [179]:
arr_2[2][3] = 777

arr_2

array([[  1,   7,  13,  19],
       [  2,   8,  14,  20],
       [  3,   9,  15, 777],
       [  4,  10,  16,  22],
       [  5,  11,  17,  23],
       [  6,  12,  18,  24]])

In [180]:
arr_1

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20, 777,  22,  23,  24]])

In [173]:
import copy

arr_3 = copy.deepcopy(arr_1.transpose())

In [174]:
arr_3

array([[100,   7,  13,  19],
       [  2,   8,  14,  20],
       [  3,   9,  15,  21],
       [  4,  10,  16,  22],
       [  5,  11,  17,  23],
       [  6,  12,  18,  24]])

In [175]:
arr_3[0][0] = 1

arr_3

array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [176]:
arr_1

array([[100,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24]])

In [181]:
arr_1 = np.arange(1,25).reshape(2,3,4)

arr_1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [183]:
arr_2 = np.transpose(arr_1, (1,0,2))

arr_2.shape

(3, 2, 4)

In [185]:
arr_3 = np.transpose(arr_1, (1,2,0))
arr_3.shape

(3, 4, 2)

In [ ]:
np.dot()

In [186]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'